name: Auto Update

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Accept OSRF software
        run: |
          sudo sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-stable.list'
          wget http://packages.osrfoundation.org/gazebo.key -O - | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install libgz-tools2-dev

      - name: Update Fuel Models
        run: ./fuel_upload.sh ${{ secrets.GAZEBO_FUEL_TOKEN }}
